### ISSUE TITLE
docker镜像目前不能访问，是不是可以继续支持更新？

### ISSUE THREAD

**Issue by houseme** [huyuanxin/polaris-server-with-config#1]
目前有多个项目依赖了您的该镜像，是不是继续支持，谢谢！

**Comment by huyuanxin** [comment]
等我回复一下，出了点问题

在 2022年5月19日，20:30，houseme ***@***.***> 写道：

﻿

**Comment by huyuanxin** [comment]
> 目前有多个项目依赖了您的该镜像，是不是继续支持，谢谢！

好的，我恢复一下，有些脚本出现了问题

**Comment by huyuanxin** [comment]
> > 目前有多个项目依赖了您的该镜像，是不是继续支持，谢谢！
> 
> 好的，我恢复一下，有些脚本出现了问题

操作的时候误删了，我这边明天会同步一次最新的版本

**Comment by houseme** [comment]
加您好友 辛苦通过一下，谢谢

**Comment by huyuanxin** [comment]
> 加您好友 辛苦通过一下，谢谢

你怎么加的，没看到🤣

**Comment by houseme** [comment]
> > 加您好友 辛苦通过一下，谢谢
> 
> 你怎么加的，没看到🤣

wx

**Comment by huyuanxin** [comment]
> > > 加您好友 辛苦通过一下，谢谢
> > 
> > 
> > 你怎么加的，没看到🤣
> 
> wx

没加我哦，加这个吧 huyuanxin1999
